### ISSUE TITLE
plugin is broken

### ISSUE THREAD

**Issue by fcrueger** [known-as-bmf/plugin.video.arteplussept#59]
Seem like it happened again. All folders are empty (change in xml/json/etc from Arte?)

Thank you for the fix.

Frederik

**Comment by known-as-bmf** [comment]
Hello and thanks for the feedback,

However, I could not reproduce the issue you described. Could you provide detailed reproduction steps ?

Have you checked your internet connectivity as well ?

**Comment by pascalou95** [comment]
Hello. I confirm fcrueger issue. Most of folders are now empty, some are not. I am using Kodi 18.1 with Libreelec 9 on RPI3 French. Internet connection is OK.

**Comment by CACO75** [comment]
Same here most of the folder are now empty. using kodi 17.6. Internet connection is fine.

**Comment by stdjulz** [comment]
Same as Pascalou95 here with version 1.02 and Kodi 18.1 on Linux Mint since a few week. I've tried to uninstall and re-install but it didn't improve it. Here with some logfile. Tell me if I can you provide more info :-)
[kodi_2019-03-10_1014_PURGED.log](https://github.com/known-as-bmf/plugin.video.arteplussept/files/2949289/kodi_2019-03-10_1014_PURGED.log)

**Comment by bergamote** [comment]
Hi, and same here with kodi 17.3

**Comment by known-as-bmf** [comment]
Sorry for the delay.

It seems that some endpoints now return a status code 400 (specifically `http://www.arte.tv/hbbtvv2/services/web/index.php/OPA/v3/videos/subcategory/ENQ/page/2/limit/10/fr`)

You can also see this in action in the TV applications (only the first few items in each category / subcategory is displayed)

Looks like they are moving to a new api : `api.arte.tv/api/opa/v3/videos/mostRecent?language=fr&page=1&limit=10&subcategory.code=AUV` but there is some authentication required here.

I pushed a small quick fix (6cb2e059ae0bac1a817974104533fda501fe2227) on master but I don't think I can do much more right now

**Comment by pascalou95** [comment]
Thank you for this Quick Fix. It's working for me.

**Comment by unwort** [comment]
Hi, sorry, i'm a totally greenhorn, so how do i use that Quick Fix?
I'm running KODI 18.1 with LibreELEC 9.0.1 on a Rasperry Pi 2.
Arte +7 Version 1.0.2
Would be great do run Arte +7 again.
I'm searching for an update every day.
Thanks!

**Comment by bergamote** [comment]
Hi unwort, not an expert so it's probably not the best way to do this but here's what I did:

- downloaded the latest [master](https://github.com/known-as-bmf/plugin.video.arteplussept/archive/master.zip) and extracted it.
- went to `/storage/.kodi/addons/` (either with ssh or mounting the sd card)
- renamed `plugin.video.arteplussept` to something else, like say `plugin.video.arteplussept-old`
- popped in the downloaded `plugin.video.arteplussept-master` folderand remove `-master` from its name
- restarted the pi

To be clear, this quickfix fixes the sections that were showing up empty but didn't bring back the ones that disappeared, like Films, probably cos those ones moved to the new API? or something?

**Comment by unwort** [comment]
Hi bergamote,
thanks for the description.
I simply deinstalled Arte +7 and reinstalled the whole thing manually from the newest full zip.
Seems the quick fix is inside.
But you're right.
It doesn't fix everything.
There are still empty folders and missing files.
Hope it will be fixed.

**Comment by jaylinski** [comment]
@known-as-bmf First: thank you for the plugin! Are you currently working on a fix? Because I'm thinking about rewriting this plugin with the new API (and in a Python 3 compatible way). I think there is a way to get it working.

Btw: ARTE is also broken in MediathekView (https://forum.mediathekview.de/topic/2574/arte-sperrt-mediathekview).

**Comment by artazis** [comment]
Hello
Some links do not work.
For example, it is impossible to see the log:
Info et société --> A ne pas manquer --> Arte Journal

**Comment by known-as-bmf** [comment]
Any update on this ? Seems to be working on matrix
